# Generated by Django 3.2.3 on 2021-05-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='showings',
            field=models.ManyToManyField(blank=True, to='CinemaBase.Show'),
        ),
    ]
