# Generated by Django 3.2.3 on 2021-05-19 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaBase', '0002_alter_cinemahall_showings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
