# Generated by Django 3.2.2 on 2021-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitles', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('disk_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('not_valid_before', models.DateTimeField(blank=True)),
                ('not_valid_after', models.DateTimeField(blank=True)),
                ('KDMKey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
