# Generated by Django 3.2.2 on 2021-05-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cpl',
            name='KDM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.kdm'),
        ),
        migrations.AddField(
            model_name='spl',
            name='CPLs',
            field=models.ManyToManyField(to='cinemabase.CPL'),
        ),
        migrations.AddField(
            model_name='spl',
            name='Effects',
            field=models.ManyToManyField(to='cinemabase.Effect'),
        ),
    ]
