# Generated by Django 3.2.2 on 2021-05-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabase', '0002_auto_20210507_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoundSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('SPLs', models.ManyToManyField(to='cinemabase.SPL')),
                ('cinema_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.kdm')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('projector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.projector')),
                ('showings', models.ManyToManyField(to='cinemabase.Show')),
                ('sound_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.soundsystem')),
            ],
        ),
    ]
