# Generated by Django 3.2.2 on 2021-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabase', '0003_cinemahall_projector_show_soundsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='showings',
            field=models.ManyToManyField(null=True, to='cinemabase.Show'),
        ),
    ]
