# Generated by Django 3.2.2 on 2021-05-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabase', '0005_alter_cinemahall_showings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='projector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.projector'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='sound_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.soundsystem'),
        ),
    ]
