# Generated by Django 3.2.2 on 2021-05-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabase', '0006_auto_20210513_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpl',
            name='KDM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.kdm'),
        ),
        migrations.AlterField(
            model_name='show',
            name='cinema_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemabase.kdm'),
        ),
        migrations.AlterField(
            model_name='spl',
            name='CPLs',
            field=models.ManyToManyField(blank=True, to='cinemabase.CPL'),
        ),
        migrations.AlterField(
            model_name='spl',
            name='Effects',
            field=models.ManyToManyField(blank=True, to='cinemabase.Effect'),
        ),
    ]
